# steps:
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         echo "Directing build request to Trigger: ${_TARGET_TRIGGER} in region: ${_REGION}"
#         gcloud builds triggers run ${_TARGET_TRIGGER} \
#           --region=${_REGION} \
#           --branch=${_TARGET_BRANCH} \
#           --substitutions=_IMAGE_NAME=${_IMAGE_NAME},_DOCKERFILE_PATH=${_DOCKERFILE_PATH},_SERVICE_NAME=${_SERVICE_NAME}

# # Required to fix the service account logging error
# options:
#   logging: CLOUD_LOGGING_ONLY

# substitutions:
#   _REGION: 'global'

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'trigger-child-build'
    script: |
      #!/usr/bin/env bash
      echo "------------------------------------------------------"
      echo "Executing Trigger: $_TRIGGER_NAME"
      echo "------------------------------------------------------"
      
      # Since automapSubstitutions is true, we use $_TRIGGER_NAME 
      # as a standard bash variable.
      gcloud builds triggers run "$_TRIGGER_NAME" \
        --region="us-central1" \
        --branch="main"

substitutions:
  _TRIGGER_NAME: "enter-name-here"

options:
  # 1. This maps _TRIGGER_NAME to a bash variable $_TRIGGER_NAME automatically
  automapSubstitutions: true
  # 2. This fixes the 'build.service_account' logging error
  logging: CLOUD_LOGGING_ONLY
